### ISSUE TITLE
Newest version error in PlayerJoinEvent

### ISSUE THREAD

**Issue by Tomasan7** [GeorgH93/Minepacks#169]
This error showed up when upgrading to 2.4 (1.16.5)
`[13:14:44 INFO]: UUID of player Danik is 8b7bb4b2-a1ed-3244-b55c-95697249ee07
[13:14:45 ERROR]: Could not pass event PlayerJoinEvent to Minepacks v2.3.24-Release
java.lang.NoClassDefFoundError: at/pcgamingfreaks/MinepacksStandalone/Bukkit/Database/Database$2
        at at.pcgamingfreaks.MinepacksStandalone.Bukkit.Database.Database.asyncLoadBackpack(Database.java:253) ~[?:?]
        at at.pcgamingfreaks.MinepacksStandalone.Bukkit.Database.Database.updatePlayerAndLoadBackpack(Database.java:280) ~[?:?]
        at at.pcgamingfreaks.MinepacksStandalone.Bukkit.Database.Database.onPlayerLoginEvent(Database.java:273) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor50.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-777]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-777]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-777]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.16.5.jar:git-Paper-777]
        at net.minecraft.server.v1_16_R3.PlayerList.postChunkLoadJoin(PlayerList.java:356) ~[patched_1.16.5.jar:git-Paper-777]
        at net.minecraft.server.v1_16_R3.PlayerList.lambda$a$1(PlayerList.java:303) ~[patched_1.16.5.jar:git-Paper-777]
        at net.minecraft.server.v1_16_R3.PlayerConnection.tick(PlayerConnection.java:316) ~[patched_1.16.5.jar:git-Paper-777]
        at net.minecraft.server.v1_16_R3.NetworkManager.a(NetworkManager.java:408) ~[patched_1.16.5.jar:git-Paper-777]
        at net.minecraft.server.v1_16_R3.ServerConnection.c(ServerConnection.java:168) ~[patched_1.16.5.jar:git-Paper-777]
        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1515) ~[patched_1.16.5.jar:git-Paper-777]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:436) ~[patched_1.16.5.jar:git-Paper-777]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1342) ~[patched_1.16.5.jar:git-Paper-777]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1130) ~[patched_1.16.5.jar:git-Paper-777]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-777]
        at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.ClassNotFoundException: at.pcgamingfreaks.MinepacksStandalone.Bukkit.Database.Database$2
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:155) ~[patched_1.16.5.jar:git-Paper-777]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:114) ~[patched_1.16.5.jar:git-Paper-777]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
        ... 19 more
[13:14:45 INFO]: Danik[/109.81.210.170:57372] logged in with entity id 61 at ([Survival]1581.7302448389353, 80.0, -3806.6410857266474)
[13:14:45 WARN]: [Minepacks] Plugin Minepacks v2.3.24-Release generated an exception while executing task 10647
java.lang.NoClassDefFoundError: at/pcgamingfreaks/MinepacksStandalone/libs/com/zaxxer/hikari/pool/HikariProxyPreparedStatement
        at at.pcgamingfreaks.MinepacksStandalone.libs.com.zaxxer.hikari.pool.ProxyFactory.getProxyPreparedStatement(ProxyFactory.java) ~[?:?]
        at at.pcgamingfreaks.MinepacksStandalone.libs.com.zaxxer.hikari.pool.ProxyConnection.prepareStatement(ProxyConnection.java:315) ~[?:?]
        at at.pcgamingfreaks.MinepacksStandalone.libs.com.zaxxer.hikari.pool.HikariProxyConnection.prepareStatement(HikariProxyConnection.java) ~[?:?]
        at at.pcgamingfreaks.MinepacksStandalone.Bukkit.Database.SQL.runStatement(SQL.java:248) ~[?:?]
        at at.pcgamingfreaks.MinepacksStandalone.Bukkit.Database.SQL.lambda$runStatementAsync$0(SQL.java:243) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.16.5.jar:git-Paper-777]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.16.5.jar:git-Paper-777]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.5.jar:git-Paper-777]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
        at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.ClassNotFoundException: at.pcgamingfreaks.MinepacksStandalone.libs.com.zaxxer.hikari.pool.HikariProxyPreparedStatement
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:155) ~[patched_1.16.5.jar:git-Paper-777]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:114) ~[patched_1.16.5.jar:git-Paper-777]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
        ... 11 more`

**Comment by GeorgH93** [comment]
This looks to me like your download is defective. Please try to download it again directly form [spigot](https://www.spigotmc.org/resources/minepacks-backpack-plugin-mc-1-7-1-16.19286/download?version=403901) or [github](https://github.com/GeorgH93/Minepacks/releases/download/v2.4/Minepacks-2.4-Release.jar).
